name: QuickerActionsDailyCrawler
on:
  schedule:
    - cron: '0 7 * * *
  workflow_dispatch:
  
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: init python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
    - run: pip install -r requirements.txt

    - name: run script
      run: cd scripts && python crawler.py

    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
